version: 0.2
env:
  parameter-store:
    SIGNER_PROFILE_ARN: 'signer-profile-arn'

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - echo Downloading AWS signer and Notation CLI.
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 142505060975.dkr.ecr.us-east-2.amazonaws.com/ecr-stack-myapp0cc8c715-62zjpfxgjbgj
  build:
    commands:
      - cd ./my-app
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t myapp:latest .
      - docker tag myapp:latest 142505060975.dkr.ecr.us-east-2.amazonaws.com/ecr-stack-myapp0cc8c715-62zjpfxgjbgj:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 142505060975.dkr.ecr.us-east-2.amazonaws.com/ecr-stack-myapp0cc8c715-62zjpfxgjbgj:latest
      - echo Writing image definitions file...
      - printf '[{"name":"my-app","imageUri":"%s"}]' 142505060975.dkr.ecr.us-east-2.amazonaws.com/ecr-stack-myapp0cc8c715-62zjpfxgjbgj:latest > $CODEBUILD_SRC_DIR/imagedefinitions.json

artifacts:
  files: imagedefinitions.json